import os
import datetime
import json
from collector import Collector
from database import ArgusDB
from notifier import SlackNotifier

def generate_report_content(cve_data, reason):
    """상세 리포트 내용 생성 (Markdown)"""
    return f"""
# Argus Threat Intelligence Report
**Target:** {cve_data['id']}
**Alert Reason:** {reason}
**Generated At:** {datetime.datetime.now()}

## Risk Assessment
- **CVSS Score:** {cve_data['cvss']}
- **EPSS Score:** {cve_data['epss']}
- **KEV Status:** {cve_data['is_kev']}

## Details
{cve_data['description']}

---
*Generated by Argus-AI (Phase 0)*
    """

def main():
    print("[*] Argus Phase 0 Scanner Started")
    
    # 1. 초기화
    collector = Collector()
    db = ArgusDB()
    notifier = SlackNotifier()
    
    # 2. 전역 데이터 로드 (KEV, EPSS)
    collector.fetch_kev()
    
    # 3. 대상 식별 (최근 변경된 CVE)
    # GitHub Scheduler가 1시간마다 돈다면 2시간 전부터 조회하여 누락 방지
    #target_cve_ids = collector.fetch_recent_cves(hours=2) 
    print("[TEST MODE] 강제로 테스트 CVE를 주입합니다.")
    target_cve_ids = [
        "CVE-2021-44228",  # Log4Shell (KEV + Critical) -> 알림 100% 발생해야 함
        "CVE-2023-34362",  # MOVEit Transfer (KEV) -> 알림 발생해야 함
        "CVE-2024-3094"    # XZ Utils (Backdoor)
    ]
    
    if not target_cve_ids:
        print("[*] No new CVEs found.")
        return
    
    if not target_cve_ids:
        print("[*] No new CVEs found.")
        return

    # EPSS 배치 로드
    collector.fetch_epss(target_cve_ids)
    
    print(f"[*] Processing {len(target_cve_ids)} CVEs...")

    for cve_id in target_cve_ids:
        try:
            # 4. 데이터 조립 (Enrichment)
            raw_data = collector.enrich_cve(cve_id)
            
            current_state = {
                "id": cve_id,
                "cvss": raw_data['cvss'],
                "epss": collector.epss_cache.get(cve_id, 0.0),
                "is_kev": cve_id in collector.kev_set,
                "description": raw_data['description']
            }
            
            # 5. DB 상태 조회
            last_record = db.get_cve(cve_id)
            last_state = last_record['last_alert_state'] if last_record else None
            
            should_alert = False
            alert_reason = ""
            
            # 6. 알림 결정 로직 (Decision Matrix)
            
            # (A) KEV 신규 등재 (최우선)
            if current_state['is_kev']:
                if not last_state or not last_state.get('is_kev'):
                    should_alert = True
                    alert_reason = "CRITICAL: CISA KEV 등재"

            # (B) EPSS >= 0.1 (High Risk)
            elif current_state['epss'] >= 0.1:
                # 첫 알림이거나, EPSS가 유의미하게 상승했을 때 (0.05 이상)
                if not last_state:
                    should_alert = True
                    alert_reason = f"HIGH RISK: EPSS {current_state['epss']}"
                elif (current_state['epss'] - last_state.get('epss', 0)) > 0.05:
                     should_alert = True
                     alert_reason = f"ESCALATION: EPSS Surge (+{(current_state['epss'] - last_state.get('epss', 0)):.2f})"

            # (C) Medium Risk (EPSS 1% 이상 + CVSS High)
            elif 0.01 <= current_state['epss'] < 0.1:
                if current_state['cvss'] >= 7.0:
                    if not last_state:
                        should_alert = True
                        alert_reason = "MEDIUM RISK: High CVSS + Rising EPSS"

            # 7. 알림 실행
            if should_alert:
                print(f"[!] Sending Alert for {cve_id}")
                
                # 리포트 생성 및 업로드
                report_content = generate_report_content(current_state, alert_reason)
                report_url = db.upload_report(cve_id, report_content)
                
                # Slack 전송
                notifier.send_alert(current_state, alert_reason, report_url['signedURL'])
                
                # DB 업데이트 데이터 준비 (알림 보냄 표시)
                upsert_data = {
                    "id": cve_id,
                    "published_date": datetime.datetime.now().isoformat(), # cve.org 원본 날짜 파싱 필요하나 MVP에선 현재 시간으로 대체 가능
                    "cvss_score": current_state['cvss'],
                    "epss_score": current_state['epss'],
                    "is_kev": current_state['is_kev'],
                    "last_alert_at": datetime.datetime.now().isoformat(),
                    "last_alert_state": current_state,
                    "updated_at": datetime.datetime.now().isoformat()
                }
            else:
                # 알림은 안 보내지만 DB 상태는 최신화 (모니터링용)
                upsert_data = {
                    "id": cve_id,
                    "cvss_score": current_state['cvss'],
                    "epss_score": current_state['epss'],
                    "is_kev": current_state['is_kev'],
                    "updated_at": datetime.datetime.now().isoformat()
                    # last_alert_at은 건드리지 않음
                }
            
            # 8. DB 저장
            db.upsert_cve(upsert_data)
            
        except Exception as e:
            print(f"[ERR] Error processing {cve_id}: {e}")
            continue

if __name__ == "__main__":
    main()